apiVersion: v1
kind: Service
metadata:
  name: whatsit-auth
  namespace: whatsit
  labels:
    name: whatsit-auth
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    name: whatsit-auth
